### ISSUE TITLE
filedescriptor out of range in select()

### ISSUE THREAD

**Issue by Alexei17** [eandersson/amqpstorm#131]
Happens when you have lots of processes (I had about 150) that constantly restart connections. Happens because of the 1024 limit on FD_SETSIZE. More info here: https://stackoverflow.com/questions/14250751/how-to-increase-filedescriptors-range-in-python-select
```

Exception in thread amqpstorm.io:
Traceback (most recent call last):
  File "/usr/lib/python3.11/threading.py", line 1038, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.11/threading.py", line 975, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python3.11/dist-packages/amqpstorm/io.py", line 259, in _process_incoming_data
    if self.poller.is_ready:
       ^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/amqpstorm/io.py", line 45, in is_ready
    ready, _, _ = self.select.select([self.fileno], [], [],
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ValueError: filedescriptor out of range in select()
```

**Comment by Anderseta** [comment]
This needs to be changed to poll() instead of select()
I am also facing this issue, did you find any workaround?

**Comment by eandersson** [comment]
> This needs to be changed to poll() instead of select() I am also facing this issue, did you find any workaround besides changing to PIKA ?

I can look at implementing poll instead of select, but could you try to bump the open file limit on your system to see if that has any affect?
https://www.cyberciti.biz/faq/linux-increase-the-maximum-number-of-open-files/

**Comment by Anderseta** [comment]
> > This needs to be changed to poll() instead of select() I am also facing this issue, did you find any workaround besides changing to PIKA ?
> 
> I can look at implementing poll instead of select, but could you try to bump the open file limit on your system to see if that has any affect? https://www.cyberciti.biz/faq/linux-increase-the-maximum-number-of-open-files/

Thank you for your answer, this changed nothing (i already had a very high custom open file limit), i am sure poll would fix this, but you should know that it does not work on windows (if i remember correctly).

I would like to point out that i changed it all to PIKA and i did not regret it, after you cross the "threadsafe" barrier of it, it is very very fast with less overhead than AMQPSTORM, it is literally a choice between performance and ease of programming, since i got a massive server running with rabbitmq, i had to choose PIKA.

In case anyone reads this
